### ISSUE TITLE
Unable to require key json file path

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/firemin#1]
### Steps to reproduce:

```bash
firemin firestore:update /courses ../api.laboratoria.la/data/00-css.json -k ./laboratoria-api-firebase-adminsdk.json
```

In the above command, `./api.laboratoria.la/data/00-css.json` holds the json file generated by `course-parser`

### Output:
```
Error: Cannot find module './laboratoria-api-firebase-adminsdk.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lazyass/.nvm/versions/node/v8.9.1/lib/node_modules/firemin/index.js:94:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by lupomontero** [comment]
@MaiaRojas, el problema es que el archivo `./laboratoria-api-firebase-adminsdk.json` parece que no existe (al ser una ruta relativa está buscando el archivo `laboratoria-api-firebase-adminsdk.json` en la misma carpeta donde estás invocando el comando. Puedes chequear si la ruta es correcta? (recuerda que _tab_ es tu amigo).

**Comment by MaiaRojas** [comment]
@lupomontero  a mi si me funciona , el problema era con @arun1595   a quien le aparece el problema.
El me pidio reportarlo.(*tab* ahora es mi amigo :wink:)

**Comment by lupomontero** [comment]
@MaiaRojas: puedes consultarle a ver si ya lo solucionó?

**Comment by FabianBravoA** [comment]
Puede que sea esto con los últimos cambios, probando en otro computador (un mac) me da la misma falla que @arun1595

**Comment by FabianBravoA** [comment]
Con ruta absoluta no falla.

**Comment by lupomontero** [comment]
Esto creo que debe quedar resuelto en https://github.com/Laboratoria/firemin/commit/ff98e15e03a14635b72c61fef34b4c7d4a124913

Pueden actualizar su versión de `firemin` a [`v1.0.0-alpha.2`](https://github.com/Laboratoria/firemin/releases/tag/v1.0.0-alpha.2)?
